name: flutter_template
description: A new Flutter project.
project_author: Yunus Karaaslan
project_author_email: karaaslan.21@hotmail.com
project_author_phone: +905319823347

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  provider: ^6.0.3
  json_annotation: ^4.5.0
  equatable: ^2.0.3
  flutter_native_splash: ^2.2.3+1
  easy_localization: ^3.0.1
  dio: ^4.0.6
  retrofit: ^3.0.1+1
  pretty_dio_logger: ^1.2.0-beta-1
  logger: ^1.1.0
  google_fonts: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  flutter_launcher_icons: ^0.9.1
  json_serializable: ^6.0.1
  build_runner: ^2.1.11
  retrofit_generator: ^4.0.1

flutter:
  uses-material-design: true

assets:
    - assets/images/
    - assets/translations/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic

flutter_native_splash:
  color: "#004566"
  image: assets/images/logo.png

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"